### ISSUE TITLE
14-Aug Deployments Checklist

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1135]
### Reveal Zambia Production

- [x] Only IRS and Dynamic-MDA intervention types
- [x] Hide server settings and clients from admin menu
- [x] Hide map on planning tool and team assignment
- [x] Authenticate via keycloak

### Reveal Namibia Production

- [x] Only IRS intervention type
- [x] Hide server settings and clients from admin menu
- [x] Hide map on planning tool and team assignment
- [x] Authenticate via keycloak

### Reveal Nigeria Production

- [x] Only Dynamic-MDA intervention type
- [x] Hide server settings and clients from admin menu
- [x] Hide map on planning tool and team assignment
- [x] Don't show the Monitor menu at all (currently no reports for Nigeria, yet)
- [x] Remove Superset slices from configs, for now
- [x] Authenticate via keycloak

### Reveal Stage

- [x] All intervention types (including MDA-Point)
- [x] Show server settings and clients from admin menu
- [x] Show map on planning tool and team assignment
- [x] Authenticate via keycloak

**Comment by moshthepitt** [comment]
For the servers that get redeployed before the Aug 14 release.  We may need to redeploy with the latest version when that version is ready.

**Comment by ciremusyoka** [comment]
@moshthepitt @p-netm i will update Namibia to use express

**Comment by moshthepitt** [comment]
Moved Thailand stuff here https://github.com/onaio/reveal-frontend/issues/1135

**Comment by moshthepitt** [comment]
Done via https://github.com/onaio/playbooks/pull/2904, https://github.com/onaio/playbooks/pull/2899, https://github.com/onaio/playbooks/tree/revealReleases, and https://github.com/onaio/opensrp-inventories/pull/127
