### ISSUE TITLE
Replace IRS Plan form with Form Page like FI

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#236]
We should be using the same PlanForm page to generate both FI and IRS plan definitions with minor differences:

- [ ] Allow a single top level Jurisdiction to be selected for the plan
- [ ] On form completion:
    - [ ] Save Plan to plans reducer
    - [ ] Redirect to IRS plan page for Jurisdiction selection

**Comment by moshthepitt** [comment]
@cKellyDesign so for this issue, we are:

- not going to send the plan to OpenSRP but only save it to the redux store
- allow only the top level jurisdiction to be selected

Yes?

**Comment by cKellyDesign** [comment]
@moshthepitt 

> not going to send the plan to OpenSRP but only save it to the redux store

If we save the plan to the redux store and navigate to `/interventionPlan/irs/draft/<id>` it will be able to load, however it may be nice to save it to OpenSRP as a draft always in case the user reloads or something. We could even capture the back button (from the Jurisdiction Selection page) and navigate to the EditPlan form page. Sorry, not trying to scope creep, either way (sending or not) should work.

> allow only the top level jurisdiction to be selected

Correct, this should be enough to get the Jurisdiction Selection page off and running.

**Comment by moshthepitt** [comment]
> If we save the plan to the redux store and navigate to /interventionPlan/irs/draft/<id> it will be able to load, however it may be nice to save it to OpenSRP as a draft always in case the user reloads or something. We could even capture the back button (from the Jurisdiction Selection page) and navigate to the EditPlan form page. Sorry, not trying to scope creep, either way (sending or not) should work. 

Will it be a problem if the plan has just the highest level jurisdiction when saved to the OpenSRP server?

**Comment by cKellyDesign** [comment]
> Will it be a problem if the plan has just the highest level jurisdiction when saved to the OpenSRP server?

Not sure that it would be an issue since it's just a draft, the Jurisdiction Selection Save as Draft/Active functionality determines all of the operational level Jurisdictions that are selected and saves those to the plan definition. So for example:

1. Save plan def with level-0 admin jurisdiction ID: v1 has one Jurisdiction ID code saved
2. Once opened in Jurisdiction Selection, without doing anything but saving as draft: v2 has all (several thousand) Operational jurisdiction IDs

This also matches the requirement of opening the Jurisdiction Selection page with all Jurisdictions selected, for the user to then go through and de-select at will.

**Comment by moshthepitt** [comment]
Thanks.  Will try get this done asap.

**Comment by moshthepitt** [comment]
### Implementation plan

- [ ] Make it possible to turn the cascading select effect off/on from JurisdictionSelect
- [ ] Create component for new IRS plan that uses PlanForm
- [ ] Cleanup
