### ISSUE TITLE
RVL-603 - WebUI Monitor Screen: Map should always show index case and Family Registration indicators should be selected by default

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#771]
https://smartregister.atlassian.net/browse/RVL-603

**Expected behavior/acceptance criteria:**

When I load the map view for a plan:

- [x] The ‘Case Confirmation' indicator should be not clickable on/off and the index case should be always visible. [#866](https://github.com/onaio/reveal-frontend/issues/866)
- [ ] Historic index cases for last three years should show [#867](https://github.com/onaio/reveal-frontend/issues/867)
- [x] The ‘Family Registration’ indicators should be selected by default when the page loads to show all structures in the focus area) [#868](https://github.com/onaio/reveal-frontend/issues/868)

 **Current state:** 
- [ ] The header of the right panel reflects the actual plan type displayed
- [ ]shows ‘Routine Investigation' for Reactive plans

**Comment by moshthepitt** [comment]
@samkanga I think it may be better to break this into smaller issues as some of them are more feasible and/or quicker to accomplish.  In any case, my comments are:

> The 'Case Confirmation' header should be differentiated from the other indicators to show that it is not clickable and always selected (perhaps different weight font or a different background)

This needs to better defined.  A design mockup is preferred.

> Historic index cases for last three years should show

Where should they show?  Where are we getting the data for them from?  This is very very vague right now.

> The ‘Family Registration’ indicators should be selected by default when the page loads to show all structures in the focus area)

To avoid ambiguity, can we get more details on this, including a mockup?

> The header of the right panel should reflect the actual plan type displayed

Can you give more details on this?  An example or mockup?

> Current state: shows ‘Routine Investigation' for Reactive plans

What does this mean?  i.e. what is the actual change that an engineer needs to make?

**Comment by samkanga** [comment]
@moshthepitt I will work on breaking down the ticket and aim to get some mock-ups.

**Comment by armageddon** [comment]
@samkanga any progress on this please?

**Comment by armageddon** [comment]
@samkanga any feedback please ?

**Comment by samkanga** [comment]
@armageddon this is yet to be picked for development

**Comment by moshthepitt** [comment]
Closed by https://github.com/onaio/reveal-frontend/pull/880
