### ISSUE TITLE
IRS Plan Map Page Issues

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#788]
- [x] IRS Plan-Jurisdiction Assignment Cleanup #537 
- [x] Load map progressively #286 
- [x] IRS Plan Page: Don't Load Jurisdictions From Superset #785 #404
- [x] Remove deprecated component lifecycle methods or convert to functional component #439 
- [x] IRS Plan Page Sometimes Does Not Load #786
- [x] IRS Plan Page Increase test coverage #669
- [x] IRS Assign Page Sometimes Does Not Load
- [x] IRS Plan Map Page DrillDown Back Button Issue #787

**Comment by moshthepitt** [comment]
Addressed partly by #977 and #929

**Comment by moshthepitt** [comment]
Finally closed by #1038
