### ISSUE TITLE
Jurisdiction Assignment Page pending work

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#986]
- [x]  make the tree structure in jurisdiction Tree reducer immutable
from [here](https://github.com/onaio/reveal-frontend/blob/714b426032f67c8d542625a8f72f9a6ec1e7eb7b/src/store/ducks/opensrp/hierarchies/index.ts#L157) the added trees objects are mutable, which seems to against our best practice of having state variables immutable. also `currentParentIdsByRootId` variable is now surplus, should be removed.
- [x] show the number of currently selected jurisdictions.
From the ui ideas [here](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/PlanAssignment/helpers/AssignedOrgs/index.tsx), we should show the number of selected jurisdictions at any time
- [x] disable checkbox for intervention types other than IRS.
For non-IRS plan types, currently in the planning tool; one should not be able to select more than one focus area to the plan.Therefore checkboxes of non-leaf nodes should be disabled and selecting one focus area should deselect any previously selected focus area
